
services:
  api:
    container_name: gerenciamento_bancario_api
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - nest-net

  db:
    container_name: gerenciamento_bancario_db
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_HOST_AUTH_METHOD: trust 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    networks:
      - nest-net

volumes:
  postgres-data:

networks:
  nest-net:
